### ISSUE TITLE
Unexpected '<ID>' exception in two simple typedef

### ISSUE THREAD

**Issue by matheusfaustino** [dstogov/php-ffi#10]
Hi, first of all, thank you for your work here. That is very impressive, I found it when I was reading about bindings on PHP. 

I'm trying to make glib bind with this ext and when the extension finds these two `typedef` it throws a exception:
```
typedef long int ptrdiff_t;
typedef long unsigned int size_t;

// throws "Uncaught FFI\ParserException: unexpected '<ID>' at line 1"
```

When I comment these lines it works, the file I'm trying to use (simplified):
```
//typedef long int ptrdiff_t;
//typedef long unsigned int size_t;
typedef int wchar_t;
typedef long double max_align_t;
typedef signed char gint8;
typedef unsigned char guint8;
typedef signed short gint16;
typedef unsigned short guint16;
typedef signed int gint32;
typedef unsigned int guint32;
typedef unsigned long guint64;
typedef signed long gint64;
typedef signed long gssize;
typedef unsigned long gsize;
typedef gint64 goffset;
typedef signed long gintptr;
typedef unsigned long guintptr;
```

ps: declaration from glib using `gcc -E`

I don't know if it's really a bug, but this behavior seems weird considering that it accepts the others `typedef` too.

Thanks in advance and thanks for your time.

**Comment by dstogov** [comment]
@matheusfaustino
ptrdiff_t and size_t are already defined in ext/FFI.
Theoretically, ext/ffi should accept compatible type re-definitions, but this is not implemented.

**Comment by matheusfaustino** [comment]
ow, I got it. Thanks ^^
