### ISSUE TITLE
Improve FFI API

### ISSUE THREAD

**Issue by SerafimArts** [dstogov/php-ffi#16]
It's no secret that PHP is famous for its disgusting and ill-conceived API and in the year 2018 PSR is already considered a **standard** of the codestyle, and not a **recommendation**.

I suggest to issue it in accordance with the recommendations of PSR-1:

**Actual**

```php
FFI::array_type(FFI\CType $type, array $dims): FFI\CType
```

**Expected**

```php
FFI::arrayType(FFI\CType $type, array $dims): FFI\CType
```

The methods are referred to as `Class::camelCase`.

You can argue on the topic "the main thing that works", but... No, well, seriously. FFI is an incredibly cool thing, but it just turns back on the fact that PHP stdlib is filled with an inconsistent API =\

-------

P.S. And ideally, I would like to get rid of all `memcpy` and call them normally, like `copyMemory` or `memcmp` => `memoryCompare` etc... 

Alternatively, transfer these methods to the instances of the `FFI\CData` object, like: `$cdata->getType()` instead of `FFI::typeof`.

**Comment by dstogov** [comment]
OK. I'll change array_type into arrayType, but won't touch FFI::typeof.

**Comment by SerafimArts** [comment]
Fine!

**Comment by SerafimArts** [comment]
judging by the [changes in the RFC](https://wiki.php.net/rfc/ffi) and new commits (https://github.com/dstogov/php-ffi/commit/6460922fe3933fb8d949976d4cd8c8cca6710fd6), I think the Issue can be closed. 

Thank you!
