### ISSUE TITLE
PHP Versions

### ISSUE THREAD

**Issue by Kashaket** [dstogov/php-ffi#27]
Hello!
This project is very helpful, so i think, i can ask about releases / version control
I've searched for extension version (php 5.6-7.0-7.1) in this repository, but, i found only one thing: there aren't any version control, so, finding a right version, which is suitable to the php version (compatible) is boring.
If you can, please, reply me, which versions (commits) is compatible with php 5.6, php 7.0, php 7.1?

**Comment by dstogov** [comment]
This project is merged into PHP and ext/ffi is going to be available with PHP 7.4.

**Comment by Kashaket** [comment]
> This project is merged into PHP and ext/ffi is going to be available with PHP 7.4.

So, there aren't any version for 5.5 < php < 7.2?

**Comment by Kashaket** [comment]
None, ok
