### ISSUE TITLE
Fields of a struct

### ISSUE THREAD

**Issue by zembrowski** [dstogov/php-ffi#41]
How to find out what fields a struct has? (The header file does not contain them.)

A simplified real-life example below.

header.h
```h
#define FFI_SCOPE "api"
#define FFI_LIB "api.so"
struct BufferApi;
typedef struct BufferApi* BufferHandle;
BufferHandle CreateBuffer(void);
```

test.php
```php
$ffi = FFI::load('header.h');
$cache = $ffi->CreateBuffer();
var_dump($cache);
```

returns
```php
object(FFI\CData:struct BufferApi*)#2 (1) {
  [0]=>
  object(FFI\CData:struct BufferApi)#3 (0) {
  }
}

```

Adjusting the header file:.

```h
struct BufferApi {
  int something;
};
```

gives the following outcome (some values of the `BufferApi` struct are static, some change):

```php
object(FFI\CData:struct BufferApi*)#2 (1) {
  [0]=>
  object(FFI\CData:struct BufferApi)#3 (1) {
    ["something"]=>
    int(-478420006)
  }
}
```

(Defined so far fourty fields as int or uint32_t without knowing what their content is.)

Disclaimer: I've got just basic C knowledge.

How can I find out what fields this struct has? And what tools should I use for this?

**Comment by dstogov** [comment]
FFI doesn't provide a way to guess the "real" fields of a structure. You'll see the content that you describe.
Sometime C libraries work with opaque (hidden) structures and APIs use just a pointer to such structures. Probably, this is your case, and you may use pointers in the same way as in C (without knowledge about  structure of content).

**Comment by zembrowski** [comment]
Thank you for your response. I asked the creators of the C library whether they can provide any further information on the fields of the structure.
